server:
  port: 80

person:
  age: 18
  name: Berlin
  map:
    k1: v1
    k2: v2
  list:
    - 1
    - 2
    - 3
  student:
    id: 78622
    username: Chole
spring:
  profiles:
    active: dev

---

server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

---

server:
  port: 8084

spring:
  config:
    activate:
      on-profile: repo
